package:
  name: ipykernel
  version: "4.0.3"

source:
  fn: ipykernel-4.0.3.tar.gz
  url: https://pypi.python.org/packages/source/i/ipykernel/ipykernel-4.0.3.tar.gz
  md5: 86b6a392e5ca727284220ea0034ec4d5
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ipykernel = ipykernel:main
    #
    # Would create an entry point called ipykernel that calls ipykernel.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - ipython
    - traitlets
    - jupyter_client

  run:
    - python
    - ipython
    - traitlets
    - jupyter_client
    - mock

test:
  # Python imports
  imports:
    - ipykernel
    - ipykernel.comm
    - ipykernel.gui
    - ipykernel.inprocess
    - ipykernel.inprocess.tests
    - ipykernel.pylab
    - ipykernel.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://ipython.org
  license: BSD License
  summary: 'IPython Kernel for Jupyter'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
