package:
  name: jupyter
  version: "1.0.0"

source:
  fn: jupyter-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/j/jupyter/jupyter-1.0.0.tar.gz
  md5: c6030444c7eb6c05a4d7b1768c72aed7
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - jupyter = jupyter:main
    #
    # Would create an entry point called jupyter that calls jupyter.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - notebook
    - jupyter_console
    - nbconvert
    - ipykernel
    - ipywidgets

  run:
    - python
    - notebook
    - jupyter_console
    - nbconvert
    - ipykernel
    - ipywidgets

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://jupyter.org
  license: BSD License
  summary: 'Jupyter metapackage. Install all the Jupyter components in one go.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
