package:
  name: ptyprocess
  version: "0.5"

source:
  fn: ptyprocess-0.5.tar.gz
  url: https://pypi.python.org/packages/source/p/ptyprocess/ptyprocess-0.5.tar.gz
  md5: 0d1ecfba622cb4e35ee157c38de18eae
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ptyprocess = ptyprocess:main
    #
    # Would create an entry point called ptyprocess that calls ptyprocess.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - ptyprocess

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/pexpect/ptyprocess
  license: ISC License (ISCL)
  summary: 'Run a subprocess in a pseudo terminal'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
