
package:
    name: ffmpeg
    version: 2.8.1

source:
    git_url: git://source.ffmpeg.org/ffmpeg.git
    git_tag: n2.8.1

build:
    number: 0

requirements:
    build:
        - x264 # [unix]
        - openssl
        - yasm # [unix]
        - mingw # [win]
    run:
        - x264 # [unix]
        - openssl

about:
    home: http://www.ffmpeg.org/
    license: GPL-2
